create-pool:
	./scripts/create_pool.sh

show-pool:
	sifnoded q clp pool ceth

show-params:
	sifnoded q clp reward-params

remove-liquidity:
	./scripts/remove_liquidity.sh

show-lp:
	./scripts/show_lp.sh

unlock-liquidity:
	./scripts/unlock_liquidity.sh
	
change-params:
	./scripts/change_params.sh

vote:
	./scripts/vote.sh