apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "block-explorer.fullname" . }}
  labels:
    {{- include "block-explorer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "block-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "block-explorer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "block-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", ". /opt/root_url.sh && ./docker/entrypoint.sh && cd /opt/bundle/bundle && node main.js"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: MONGO_URL
              value: "mongodb://{{ include "block-explorer.fullname" . }}-mongodb:27017/meteor"
            - name: PORT
              value: "3000"
            - name: METEOR_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "block-explorer.fullname" . }}-meteor
                  key: meteor_settings
          volumeMounts:
            - mountPath: /opt/root_url.sh
              name: {{ include "block-explorer.fullname" . }}-url
              subPath: root_url.sh
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "block-explorer.fullname" . }}-url
        configMap:
          name: {{ include "block-explorer.fullname" . }}-url
          items:
            - key: root_url
              path: 'root_url.sh'
          defaultMode: 0755
