apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "block-explorer.fullname" . }}
  labels:
    {{- include "block-explorer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "block-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "block-explorer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "block-explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: root-url
          image: alpine/k8s:1.18.2
          command: ["/scripts/root-url.sh", '{{ include "block-explorer.fullname" . }}-root-url']
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "./docker/entrypoint.sh && cd /opt/bundle/bundle && node main.js"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "block-explorer.fullname" . }}-root-url
                  key: rootURL
            - name: MONGO_URL
              value: "mongodb://{{ include "block-explorer.fullname" . }}-mongodb:27017/meteor"
            - name: PORT
              value: "3000"
            - name: METEOR_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "block-explorer.fullname" . }}-settings
                  key: settings
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "block-explorer.fullname" . }}-scripts
            defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
