kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "block-explorer.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "block-explorer.serviceAccountName" . }}
  namespace: {{ include "block-explorer.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
