apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logstash.fullname" . }}-elasticsearch
data:
  USERNAME: {{ .Values.logstash.args.elasticsearchUsername | b64enc | quote }}
  PASSWORD: {{ .Values.logstash.args.elasticsearchPassword | b64enc | quote }}
type: Opaque
