// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sifnode/whitelist/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	AdminAccount string          `protobuf:"bytes,1,opt,name=admin_account,json=adminAccount,proto3" json:"admin_account,omitempty"`
	Whitelist    *DenomWhitelist `protobuf:"bytes,2,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f18f56a2888c4dc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetAdminAccount() string {
	if m != nil {
		return m.AdminAccount
	}
	return ""
}

func (m *GenesisState) GetWhitelist() *DenomWhitelist {
	if m != nil {
		return m.Whitelist
	}
	return nil
}

type DenomWhitelist struct {
	DenomWhitelistEntries []*DenomWhitelistEntry `protobuf:"bytes,1,rep,name=denom_whitelist_entries,json=denomWhitelistEntries,proto3" json:"denom_whitelist_entries,omitempty"`
}

func (m *DenomWhitelist) Reset()         { *m = DenomWhitelist{} }
func (m *DenomWhitelist) String() string { return proto.CompactTextString(m) }
func (*DenomWhitelist) ProtoMessage()    {}
func (*DenomWhitelist) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f18f56a2888c4dc, []int{1}
}
func (m *DenomWhitelist) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomWhitelist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomWhitelist.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomWhitelist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomWhitelist.Merge(m, src)
}
func (m *DenomWhitelist) XXX_Size() int {
	return m.Size()
}
func (m *DenomWhitelist) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomWhitelist.DiscardUnknown(m)
}

var xxx_messageInfo_DenomWhitelist proto.InternalMessageInfo

func (m *DenomWhitelist) GetDenomWhitelistEntries() []*DenomWhitelistEntry {
	if m != nil {
		return m.DenomWhitelistEntries
	}
	return nil
}

type DenomWhitelistEntry struct {
	IsWhitelisted bool   `protobuf:"varint,1,opt,name=is_whitelisted,json=isWhitelisted,proto3" json:"is_whitelisted,omitempty"`
	Denom         string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Decimals      int64  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (m *DenomWhitelistEntry) Reset()         { *m = DenomWhitelistEntry{} }
func (m *DenomWhitelistEntry) String() string { return proto.CompactTextString(m) }
func (*DenomWhitelistEntry) ProtoMessage()    {}
func (*DenomWhitelistEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f18f56a2888c4dc, []int{2}
}
func (m *DenomWhitelistEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomWhitelistEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomWhitelistEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomWhitelistEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomWhitelistEntry.Merge(m, src)
}
func (m *DenomWhitelistEntry) XXX_Size() int {
	return m.Size()
}
func (m *DenomWhitelistEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomWhitelistEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DenomWhitelistEntry proto.InternalMessageInfo

func (m *DenomWhitelistEntry) GetIsWhitelisted() bool {
	if m != nil {
		return m.IsWhitelisted
	}
	return false
}

func (m *DenomWhitelistEntry) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomWhitelistEntry) GetDecimals() int64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sifnode.whitelist.v1.GenesisState")
	proto.RegisterType((*DenomWhitelist)(nil), "sifnode.whitelist.v1.DenomWhitelist")
	proto.RegisterType((*DenomWhitelistEntry)(nil), "sifnode.whitelist.v1.DenomWhitelistEntry")
}

func init() { proto.RegisterFile("sifnode/whitelist/v1/types.proto", fileDescriptor_2f18f56a2888c4dc) }

var fileDescriptor_2f18f56a2888c4dc = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0x86, 0xe9, 0x47, 0x3e, 0x03, 0xe5, 0x67, 0x51, 0x31, 0x4e, 0x58, 0x4c, 0x26, 0xa8, 0xc9,
	0xb8, 0x70, 0x26, 0xe0, 0x15, 0x48, 0x34, 0xec, 0xcb, 0x82, 0xc4, 0x0d, 0x29, 0xd3, 0x03, 0x9c,
	0x84, 0x69, 0x09, 0x2d, 0x20, 0x77, 0xe1, 0x65, 0xb9, 0x64, 0xe9, 0xd2, 0xc0, 0x8d, 0x18, 0x8a,
	0x0c, 0x1a, 0x59, 0xb8, 0x9b, 0xf3, 0xcc, 0xd3, 0xf3, 0xe6, 0xe4, 0xa5, 0x81, 0xc1, 0xa1, 0xd2,
	0x12, 0xe2, 0xe5, 0x18, 0x2d, 0x4c, 0xd0, 0xd8, 0x78, 0xd1, 0x8c, 0xed, 0x6a, 0x0a, 0x26, 0x9a,
	0xce, 0xb4, 0xd5, 0xac, 0xf6, 0x65, 0x44, 0x99, 0x11, 0x2d, 0x9a, 0xf5, 0xda, 0x48, 0x8f, 0xb4,
	0x13, 0xe2, 0xdd, 0xd7, 0xde, 0x6d, 0x2c, 0x69, 0xb9, 0x03, 0x0a, 0x0c, 0x9a, 0xae, 0x15, 0x16,
	0xd8, 0x15, 0xad, 0x08, 0x99, 0xa2, 0xea, 0x8b, 0x24, 0xd1, 0x73, 0x65, 0x3d, 0x12, 0x90, 0xb0,
	0xc8, 0xcb, 0x0e, 0x3e, 0xec, 0x19, 0x6b, 0xd3, 0x62, 0xb6, 0xda, 0xfb, 0x17, 0x90, 0xb0, 0xd4,
	0xba, 0x8e, 0x4e, 0x85, 0x46, 0x8f, 0xa0, 0x74, 0xda, 0x3b, 0x10, 0x7e, 0x7c, 0xd6, 0x30, 0xb4,
	0xfa, 0xf3, 0x27, 0x13, 0xf4, 0x52, 0xee, 0x48, 0x3f, 0x93, 0xfa, 0xa0, 0xec, 0x0c, 0xc1, 0x78,
	0x24, 0xc8, 0x87, 0xa5, 0xd6, 0xed, 0x5f, 0x32, 0x9e, 0x94, 0x9d, 0xad, 0xf8, 0x85, 0xfc, 0x05,
	0x11, 0x4c, 0x43, 0xd1, 0xf3, 0x13, 0x36, 0xbb, 0xa1, 0x55, 0x34, 0xc7, 0x58, 0x90, 0xee, 0xea,
	0x02, 0xaf, 0xa0, 0xe9, 0x1d, 0x21, 0xab, 0xd1, 0xff, 0x6e, 0xad, 0x3b, 0xb9, 0xc8, 0xf7, 0x03,
	0xab, 0xd3, 0x82, 0x84, 0x04, 0x53, 0x31, 0x31, 0x5e, 0x3e, 0x20, 0x61, 0x9e, 0x67, 0x73, 0xbb,
	0xf3, 0xb6, 0xf1, 0xc9, 0x7a, 0xe3, 0x93, 0x8f, 0x8d, 0x4f, 0x5e, 0xb7, 0x7e, 0x6e, 0xbd, 0xf5,
	0x73, 0xef, 0x5b, 0x3f, 0xf7, 0x7c, 0x37, 0x42, 0x3b, 0x9e, 0x0f, 0xa2, 0x44, 0xa7, 0x71, 0x17,
	0x87, 0xc9, 0x58, 0xa0, 0x8a, 0x0f, 0xcd, 0xbe, 0x7c, 0xeb, 0xd6, 0x15, 0x3b, 0x38, 0x73, 0x6d,
	0xdd, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x80, 0xd6, 0xe9, 0xaa, 0xfd, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Whitelist != nil {
		{
			size, err := m.Whitelist.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AdminAccount) > 0 {
		i -= len(m.AdminAccount)
		copy(dAtA[i:], m.AdminAccount)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AdminAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomWhitelist) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomWhitelist) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomWhitelist) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomWhitelistEntries) > 0 {
		for iNdEx := len(m.DenomWhitelistEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomWhitelistEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *DenomWhitelistEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomWhitelistEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomWhitelistEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decimals != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.IsWhitelisted {
		i--
		if m.IsWhitelisted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AdminAccount)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Whitelist != nil {
		l = m.Whitelist.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *DenomWhitelist) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DenomWhitelistEntries) > 0 {
		for _, e := range m.DenomWhitelistEntries {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *DenomWhitelistEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsWhitelisted {
		n += 2
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovTypes(uint64(m.Decimals))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdminAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Whitelist == nil {
				m.Whitelist = &DenomWhitelist{}
			}
			if err := m.Whitelist.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomWhitelist) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomWhitelist: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomWhitelist: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomWhitelistEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomWhitelistEntries = append(m.DenomWhitelistEntries, &DenomWhitelistEntry{})
			if err := m.DenomWhitelistEntries[len(m.DenomWhitelistEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomWhitelistEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomWhitelistEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomWhitelistEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsWhitelisted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsWhitelisted = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
