run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  enable:
    - bodyclose
    # WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    # - deadcode
    # x/tokenregistry/client/cli/query.go:9:2: import 'github.com/cosmos/cosmos-sdk/client' is not allowed from list 'Main' (depguard)
    # - depguard
    - dogsled
    - goconst
    # - gocritic
    # - gofmt
    # - goimports
    # - golint
    # x/clp/client/cli/query.go:49:17: unused-parameter: parameter 'queryRoute' seems to be unused, consider removing or renaming it as _ (revive)
    # - revive
    - gosec
    - govet
    - ineffassign
    # - interfacer
    # this is deprecated/obsolete
    # - maligned
    - misspell
    - nakedret
    - prealloc
    # - scopelint
    - exportloopref
    - staticcheck
    # WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    # - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - misspell
    - errcheck
  disable:
    - gosimple

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - revive
    - text: "don't use underscores in Go names"
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive
    - text: "ST1003:"
      linters:
        - stylecheck
    - text: "SA1019:"
      linters:
        - staticcheck
    - path: test/
      linters:
        - deadcode
        - unused
        - ineffassign
        - prealloc
        - staticcheck
    # Not a real issue here, so ignore
    - path: x/clp/keeper/pureCalculation_test.go
      text: "G113:"
      linters:
        - gosec

linters-settings:
  goconst:
    min-occurrences: 4
  dogsled:
    max-blank-identifiers: 7
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
