run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - goconst
#    - gocritic
#    - gofmt
#    - goimports
    - golint
#    - revive : this is replacement for golint above which is deprecated
    - gosec
    - govet
    - ineffassign
#    - interfacer
# this is deprecated/obsolete
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
#    - exportloopref : this is replacement for scopelint which is deprecated
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - misspell
    - errcheck
  disable:
    - gosimple

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - golint
    - text: "don't use underscores in Go names"
      linters:
        - golint
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: "ST1003:"
      linters:
        - stylecheck

linters-settings:
  goconst:
    min-occurrences: 4
  dogsled:
    max-blank-identifiers: 7
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
