run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  enable:
    - bodyclose
    - depguard
    - goconst
    - gocritic
    - revive
    - gosec
    - gofumpt
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - misspell
    - nolintlint
    - errcheck
    - gosimple

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "don't use underscores in Go names"
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive
