{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cryptoeconomics.fullname" . }}
  labels:
  {{ include "cryptoeconomics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  {{- end -}}
