apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptoeconomics.fullname" . }}
  labels:
    {{- include "cryptoeconomics.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "cryptoeconomics.selectorLabels" . | nindent 4 }}
