create-pool:
	./scripts/create_pool.sh

show-pool:
	sifnoded q clp pool ceth

deploy-contract:
	./scripts/deploy_and_instantiate.sh

swap:
	./scripts/swap_rowan_ceth.sh

show-contract-balance:
	sifnoded q bank balances sif14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s62cvu6
