apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ebrelayer.fullname" . }}
type: Opaque
data:
  ethPrivateKey: {{ .Values.ebrelayer.env.ethPrivateKey | b64enc }}
  mnemonic: {{ .Values.ebrelayer.env.mnemonic | b64enc }}
