replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-cryptoeconomics: "kv-v2/-=app_region=-/-=app_env=-/cryptoeconomics"
  vault.hashicorp.com/ca-cert: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  vault.hashicorp.com/role: cryptoeconomics
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-inject-template-cryptoeconomics: |
    {{- with secret "kv-v2/-=app_region=-/-=app_env=-/cryptoeconomics" -}}
      export HEADER_SECRET="{{ .Data.data.HEADER_SECRET }}"
      export SNAPSHOT_URL="{{ .Data.data.SNAPSHOT_URL }}"
    {{- end }}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/cryptoeconomics
  pullPolicy: Always
  tag: "testnet"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: cryptoeconomics.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 8Gi
  limits:
    memory: 16Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
