apiVersion: v1
appVersion: 7.10.2
description: Official Elastic helm chart for Logstash
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/logstash.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: logstash
sources:
- https://github.com/elastic/logstash
version: 7.10.2
