package types

// clp module event types

const (
	EventTypeCreatePool                          = "created_new_pool"
	EventTypeDecommissionPool                    = "decommission_pool"
	EventTypeAddNewPmtpPolicy                    = "pmtp_new_policy"
	EventTypeEndPmtpPolicy                       = "pmtp_end_policy"
	EventTypeCreateLiquidityProvider             = "created_new_liquidity_provider"
	EventTypeAddLiquidity                        = "added_liquidity"
	EventTypeRemoveLiquidity                     = "removed_liquidity"
	EventTypeRequestUnlock                       = "request_unlock_liquidity"
	EventTypeCancelUnlock                        = "cancel_unlock_liquidity"
	EventTypeSwap                                = "swap_successful"
	EventTypeSwapFailed                          = "swap_failed"
	EventTypeUpdateLiquidityProtectionParams     = "liquidity_protection_update_params"
	EventTypeUpdateLiquidityProtectionRateParams = "liquidity_protection_update_rate_params"
	EventTypeAddNewProviderDistributionPolicy    = "lppd_new_policy"
	EventTypeProviderDistributionDistribution    = "lppd_distribution"
	EventTypeProcessedRemovalQueue               = "processed_removal_queue"
	EventTypeQueueRemovalRequest                 = "queue_removal_request"
	EventTypeDequeueRemovalRequest               = "dequeue_removal_request"
	EventTypeProcessRemovalError                 = "process_removal_error"
	EventTypeAddLiquidityToRewardsBucket         = "added_liquidity_to_rewards_bucket"
	AttributeKeyThreshold                        = "min_threshold"
	AttributeKeySwapAmount                       = "swap_amount"
	AttributeKeyLiquidityFee                     = "liquidity_fee"
	AttributeKeyPriceImpact                      = "price_impact"
	AttributeKeyInPool                           = "in_pool"
	AttributeKeyOutPool                          = "out_pool"
	AttributePmtpBlockRate                       = "pmtp_block_rate"
	AttributePmtpCurrentRunningRate              = "pmtp_current_running_rate"
	AttributeKeyPool                             = "pool"
	AttributeKeyHeight                           = "height"
	AttributeKeyLiquidityProvider                = "liquidity_provider"
	AttributeKeyUnits                            = "liquidity_units"
	AttributeKeyPmtpPolicyParams                 = "pmtp_policy_params"
	AttributeKeyPmtpRateParams                   = "pmtp_rate_params"
	AttributeKeyLiquidityProtectionParams        = "liquidity_protection_params"
	AttributeKeyLiquidityProtectionRateParams    = "liquidity_protection_rate_params"
	AttributeKeyProviderDistributionParams       = "lppd_params"
	AttributeValueCategory                       = ModuleName
	AttributeProbiverDistributionAmount          = "lppd_distribution_amount"
	AttributeProbiverDistributionReceiver        = "lppd_distribution_receiver"
	AttributeKeyError                            = "error"
	AttributeKeyDenom                            = "denom"
	AttributeKeyAmount                           = "amount"
)
