#!/usr/bin/env bash

function header (){
    echo "======================"
    echo "${1}"
    echo "======================"
}

function footer (){
    echo "======================"
    echo ""
}

read -p "What AWS profile do you want to use: \n $(cat ~/.aws/config | grep "\[profile" | grep -v "#") [devnet]:" AWS_PROFILE
AWS_PROFILE=${AWS_PROFILE:-devnet}