openapi: 3.0.1
info:
  title:  Sifnode - OpenAPI spec
  description: OpenAPI spec for sifnode
  version: '0.0.1'
paths:
  /:
    get:
      description: Root Path
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
              example:
                Hello World
  /clp/getPools:
    get:
      description: Get CLP List
      responses:
        '200':
          description: CLP Pools Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        external_asset:
                          type: object
                          properties:
                            symbol:
                              type: stringg
                        external_asset_balance:
                          type: string
                        native_asset_balance:
                          type: string
                        pool_units:
                          type: string
                        pool_address:
                          type: string
                  height:
                    type: string
  /clp/getLiquidityProvider:
    get:
      description: Get Liqudity provider details
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
          example: ceth
        - name: lpAddress
          in: query
          schema:
            type: string
          example: sif18agvfsynv8phnxxvs75t2te0286eu8t6msgc0r
      responses:
        '200':
          description: Liquidy details Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      liquidity_provider_units:
                        type: string
                      liquidity_provider_address:
                        type: string
                      asset:
                        type: object
                        properties:
                          symbol:
                            type: string
                  height:
                    type: string
  /clp/getPool:
    get:
      description: Get Pool details
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
          example: ceth
      responses:
        '200':
          description: Pool Detail Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      external_asset:
                        type: object
                        properties:
                          symbol:
                            type: string
                      external_asset_balance:
                        type: string
                      native_asset_balance:
                        type: string
                      pool_units:
                        type: string
                      pool_address:
                        type: string
                  height:
                    type: string
  /clp/decommissionPool:
    post:
      description:  Decommision Pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                base_req:
                  type: object
                  properties:
                    chain_id:
                      type: string
                    from:
                      type: string
                signer:
                  type: string
      responses:
        '200':
          description: Decommision Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: object
                    properties:
                      msg:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: object
                              properties:
                                symbol:
                                  type: string
                                signer:
                                  type: string
                      fee:
                        type: object
                        properties:
                          amount:
                            type: array
                            items:
                              type: string
                          gas:
                            type: string
                      memo:
                        type: string
                      signatures: {}
  /clp/removeLiquidity:
    post:
      description: Remove Liquidity from pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                external_asset:
                  type: object
                  properties:
                    symbol:
                      type: string
                w_basis_points:
                  type: string
                base_req:
                  type: object
                  properties:
                    chain_id:
                      type: string
                    from:
                      type: string
                asymmetry:
                  type: string
                signer:
                  type: string
      responses:
        '200':
          description: Remove Liquidity Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: object
                    properties:
                      msg:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: object
                              properties:
                                Signer:
                                  type: string
                                Asymmetry:
                                  type: string
                                ExternalAsset:
                                  type: object
                                  properties:
                                    symbol:
                                      type: string
                                WBasisPoints:
                                  type: string
                      fee:
                        type: object
                        properties:
                          amount:
                            type: array
                            items:
                              type: string
                          gas:
                            type: string
                      memo:
                        type: string
                      signatures: {}
  /clp/addLiquidity:
    post:
      description: Add Liquidity to Pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                external_asset:
                  type: object
                  properties:
                    symbol:
                      type: string
                external_asset_amount:
                  type: string
                native_asset_amount:
                  type: string
                base_req:
                  type: object
                  properties:
                    chain_id:
                      type: string
                    from:
                      type: string
                signer:
                  type: string
      responses:
        '200':
          description:  Add Liquidity Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: object
                    properties:
                      msg:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: object
                              properties:
                                Signer:
                                  type: string
                                ExternalAsset:
                                  type: object
                                  properties:
                                    symbol:
                                      type: string
                                NativeAssetAmount:
                                  type: string
                                ExternalAssetAmount:
                                  type: string
                      fee:
                        type: object
                        properties:
                          amount:
                            type: array
                            items:
                              type: string
                          gas:
                            type: string
                      memo:
                        type: string
                      signatures: {}
  /clp/swap:
    post:
      description: Swap tokens
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sent_asset:
                  type: object
                  properties:
                    symbol:
                      type: string
                base_req:
                  type: object
                  properties:
                    chain_id:
                      type: string
                    from:
                      type: string
                received_asset:
                  type: object
                  properties:
                    symbol:
                      type: string
                signer:
                  type: string
                sent_amount:
                  type: string
      responses:
        '200':
          description: Swap Tokens response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: object
                    properties:
                      msg:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: object
                              properties:
                                Signer:
                                  type: string
                                SentAmount:
                                  type: string
                                ReceivedAsset:
                                  type: object
                                  properties:
                                    symbol:
                                      type: string
                                SentAsset:
                                  type: object
                                  properties:
                                    symbol:
                                      type: string
                      fee:
                        type: object
                        properties:
                          amount:
                            type: array
                            items:
                              type: string
                          gas:
                            type: string
                      memo:
                        type: string
                      signatures: {}
  /clp/createPool:
    post:
      description: Create new pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                external_asset:
                  type: object
                  properties:
                    symbol:
                      type: string
                external_asset_amount:
                  type: string
                native_asset_amount:
                  type: string
                base_req:
                  type: object
                  properties:
                    chain_id:
                      type: string
                    from:
                      type: string
                signer:
                  type: string
      responses:
        '200':
          description: Create Pool Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  value:
                    type: object
                    properties:
                      msg:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: object
                              properties:
                                Signer:
                                  type: string
                                ExternalAsset:
                                  type: object
                                  properties:
                                    symbol:
                                      type: string
                                NativeAssetAmount:
                                  type: string
                                ExternalAssetAmount:
                                  type: string
                      fee:
                        type: object
                        properties:
                          amount:
                            type: array
                            items:
                              type: string
                          gas:
                            type: string
                      memo:
                        type: string
                      signatures: {}
