{{- if .Values.ebrelayer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sifnode.fullname" . }}-ebrelayer
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}-ebrelayer
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sifnode.selectorLabels" . | nindent 6 }}-ebrelayer
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sifnode.selectorLabels" . | nindent 8 }}-ebrelayer
    spec:
      serviceAccountName: {{ include "sifnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ebrelayer.image.repository }}:{{ .Values.ebrelayer.image.tag }}"
          imagePullPolicy: {{ .Values.ebrelayer.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "ebrelayer init $NODE_HOST $ETH_WEBSOCKET_ADDRESS $ETH_BRIDGE_REGISTRY_ADDRESS $MONIKER \"$MNEMONIC\" --chain-id $CHAINNET"]
          env:
            - name: NODE_HOST
              value: "tcp://{{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local:26657"
            - name: CHAINNET
              value: {{ .Values.sifnode.env.chainnet }}
            - name: ETH_WEBSOCKET_ADDRESS
              value: {{ .Values.ebrelayer.env.ethWebsocketAddress }}
            - name: ETH_BRIDGE_REGISTRY_ADDRESS
              value: {{ .Values.ebrelayer.env.ethBridgeRegistryAddress }}
            - name: MONIKER
              value: {{ .Values.ebrelayer.env.moniker }}
            - name: ETHEREUM_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sifnode.fullname" . }}-ebrelayer
                  key: ethPrivateKey
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "sifnode.fullname" . }}-ebrelayer
                  key: mnemonic
          livenessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
