apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sifnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sifnode.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sifnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          volumeMounts:
            - name: data
              mountPath: /root/
          {{- if .Values.sifnode.env.peerAddress }}
          args: ["-c", "sifgen node create $CHAINNET $MONIKER \"$MNEMONIC\" $PEER_ADDRESS $GENESIS_URL; sifnoded start --rpc.laddr tcp://0.0.0.0:26657"]
          {{- else }}
          args: ["-c", "sifgen node create $CHAINNET $MONIKER \"$MNEMONIC\"; sifnoded start --rpc.laddr tcp://0.0.0.0:26657"]
          {{- end }}
          ports:
            - name: port-26656
              containerPort: 26656
              protocol: TCP
            - name: port-26657
              containerPort: 26657
              protocol: TCP
          env:
            - name: CHAINNET
              value: {{ .Values.sifnode.env.chainnet }}
            - name: MONIKER
              value: {{ .Values.sifnode.env.moniker }}
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "sifnode.fullname" . }}
                  key: mnemonic
            - name: SIF_ID
              value: {{ .Values.sifnode.env.sifId }}
            - name: PEER_ADDRESS
              value: {{ .Values.sifnode.env.peerAddress }}
            - name: GENESIS_URL
              value: {{ .Values.sifnode.env.genesisURL }}
          livenessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "sifnode.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
