apiVersion: v1
kind: Service
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sifnode.service.type }}
  ports:
    - port: 26656
      protocol: TCP
      name: p2p
    - port: 26657
      protocol: TCP
      name: rpc
  selector:
    {{- include "sifnode.selectorLabels" . | nindent 4 }}
