apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.sifnodeName }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageclass }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
