apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sifnode.fullname" . }}
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sifnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sifnode.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "sifnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: external-ip
          image: alpine/k8s:1.18.2
          command: ["/scripts/external-ip.sh", "sifnode", "$MONIKER", '{{ include "sifnode.fullname" . }}-external-ip']
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          env:
            - name: MONIKER
              value: {{ .Values.sifnode.env.moniker }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          volumeMounts:
            - name: data
              mountPath: /root/
          {{- if .Values.sifnode.env.peerAddress }}
          args: ["-c", "sifgen node create $CHAINNET $MONIKER \"$MNEMONIC\" $EXTERNAL_IP $PEER_ADDRESS $GENESIS_URL; sifnoded start --rpc.laddr tcp://0.0.0.0:26657"]
          {{- else }}
          args: ["-c", "sifgen node create $CHAINNET $MONIKER \"$MNEMONIC\" $EXTERNAL_IP; sifnoded start --rpc.laddr tcp://0.0.0.0:26657"]
          {{- end }}
          ports:
            - name: p2p
              containerPort: 26656
              protocol: TCP
            - name: rpc
              containerPort: 26657
              protocol: TCP
          env:
            - name: CHAINNET
              value: {{ .Values.sifnode.env.chainnet }}
            - name: MONIKER
              value: {{ .Values.sifnode.env.moniker }}
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ include "sifnode.fullname" . }}
                  key: mnemonic
            - name: EXTERNAL_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sifnode.fullname" . }}-external-ip
                  key: externalIP
            - name: PEER_ADDRESS
              value: {{ .Values.sifnode.env.peerAddress }}
            - name: GENESIS_URL
              value: {{ .Values.sifnode.env.genesisURL }}
          livenessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 26657
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "sifnode.fullname" . }}{{- end }}
      {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ include "sifnode.fullname" . }}-scripts
          defaultMode: 0777
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
