apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sifnode.fullname" . }}-cli
  labels:
    {{- include "sifnode.labels" . | nindent 4 }}-cli
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sifnode.selectorLabels" . | nindent 6 }}-cli
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sifnode.selectorLabels" . | nindent 8 }}-cli
    spec:
      serviceAccountName: {{ include "sifnode.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-cli
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "sifnodecli rest-server --unsafe-cors --laddr tcp://0.0.0.0:1317 --node $NODE_HOST --trace"]
          ports:
            - name: port-1317
              containerPort: 1317          
          env:
            - name: NODE_HOST
              value: "tcp://{{ .Chart.Name }}.{{ .Release.Namespace }}.svc.cluster.local:26657"
          livenessProbe:
            tcpSocket:
              port: 1317
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1317
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
