#!/bin/bash

set -eu

######################################
# ARG PARSING

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -t|--type)
      TYPE="$2"
      shift # past argument
      shift # past value
      ;;
    -a|--chain)
      CHAIN="$2"
      shift # past argument
      shift # past value
      ;;
    -b|--connection)
      CONNECTION="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

######################################


case $CHAIN in

  sif)
    CHAIN_DIR=sif
    ;;

  terra)
    CHAIN_DIR=terra
    ;;

  *)
    echo -n "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

CHAIN_DIR=$CHAIN_DIR/$CONNECTION

case $TYPE in

  send)
    OUT_FILE="clean/$CHAIN_DIR/send_packet_seq.data"
    FILES="data/$CHAIN_DIR/send/*"
    QUERY='.txs[].logs[].events[]|select(.type=="send_packet").attributes[]|select(.key=="packet_sequence").value|tonumber'
    ;;

  ack)
    OUT_FILE="clean/$CHAIN_DIR/ack_packet_seq.data"
    FILES="data/$CHAIN_DIR/ack/*"
    QUERY='.txs[].logs[].events[]|select(.type=="acknowledge_packet").attributes[]|select(.key=="packet_sequence").value|tonumber'
    ;;

  timeout)
    OUT_FILE="clean/$CHAIN_DIR/timeout_packet_seq.data"
    FILES="data/$CHAIN_DIR/timeout/*"
    QUERY='.txs[].logs[].events[]|select(.type=="timeout_packet").attributes[]|select(.key=="packet_sequence").value|tonumber'
    ;;

  rcv)
    OUT_FILE="clean/$CHAIN_DIR/rcv_packet_seq.data"
    FILES="data/$CHAIN_DIR/rcv/*"
    QUERY='.txs[].logs[].events[]|select(.type=="recv_packet").attributes[]|select(.key=="packet_sequence").value|tonumber'
    ;;

  *)
    echo -n "Unknown type: $TYPE"
    exit 1
    ;;
esac

mkdir -p clean/$CHAIN_DIR


rm -f $OUT_FILE

for f in $FILES
do
  jq $QUERY $f >> $OUT_FILE
done

sort -no $OUT_FILE $OUT_FILE



