apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "-=app_name=-.fullname" . }}
  labels:
    {{- include "-=app_name=-.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "-=app_name=-.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "-=app_name=-.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "-=app_name=-.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          {{- range $key, $val := .Values.-=app_name=-.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", ". ~/.profile && wget $(curl -s https://api.github.com/repos/binance-chain/bsc/releases/latest |grep browser_ |grep -=binance_env=- |cut -d\" -f4) && unzip -=binance_env=-.zip && geth --datadir node init genesis.json && geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof"]
          volumeMounts:
            - name: data
              mountPath: /binancenode
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if and .Values.persistence.enabled (not .Values.persistence.hostPath) }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "-=app_name=-.fullname" . }}{{- end }}
        {{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        hostPath:
          path: {{ .Values.persistence.hostPath }}
          type: DirectoryOrCreate
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
