#!/bin/sh

SIFCHAIN_ID=sifchain-devnet-1 \
  COSMOS_BASE_DENOM=uphoton \
  COSMOS_CHANNEL_ID=channel-114 \
  COSMOS_COUNTERPARTY_CHANNEL_ID=channel-26 \
  COSMOS_CHAIN_ID=cosmoshub-testnet \
  AKASH_CHANNEL_ID=channel-110 \
  AKASH_COUNTERPARTY_CHANNEL_ID=channel-63 \
  AKASH_CHAIN_ID=akash-testnet-6 \
  IRIS_BASE_DENOM=unyan \
  IRIS_CHANNEL_ID=channel-117 \
  IRIS_COUNTERPARTY_CHANNEL_ID=channel-24 \
  IRIS_CHAIN_ID=nyancat-8 \
  PERSISTENCE_CHANNEL_ID=channel-120 \
  PERSISTENCE_COUNTERPARTY_CHANNEL_ID=channel-25 \
  PERSISTENCE_CHAIN_ID=test-core-1 \
  CRYPTO_ORG_CHANNEL_ID=channel-118 \
  CRYPTO_ORG_COUNTERPARTY_CHANNEL_ID=channel-31 \
  CRYPTO_ORG_CHAIN_ID=crypto-org-chain-mainnet-1 \
  SENTINEL_CHANNEL_ID=channel-111 \
  SENTINEL_COUNTERPARTY_CHANNEL_ID=CHANNEL-35 \
  SENTINEL_CHAIN_ID=sentinelhub-2 ./template/generate-all-ibc.sh
