replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret--=app_name=-: "kv-v2/-=app_region=-/-=env=-/-=app_name=-"
  vault.hashicorp.com/ca-cert: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  vault.hashicorp.com/role: -=app_name=-
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-inject-template--=app_name=-: |
    {{- with secret "kv-v2/-=app_region=-/-=env=-/-=app_name=-" -}}
      export MONGO_URL={{ .Data.data.MONGO_URL }}
      export PORT={{ .Data.data.PORT }}
    {{- end }}

podSecurityContext: {}

securityContext: {}

image:
  repository: sifchain/block-explorer
  pullPolicy: Always
  tag: "testnet"

blockExplorer:
  args:
    mongoUsername: "mongodb"
    mongoPassword:
    mongoDatabase: "block_explorer"
    rootURL: "-=ROOT_URL=-"
  env:
    chainnet: "-=CHAIN_NET=-"
    genesisURL: "-=GENESIS_URL=-"
    remote:
      rpcURL: "-=RPC_URL=-"
      apiURL: "-=API_URL=-"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: block-explorer.local
      paths: []
  tls: []

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    memory: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate

nodeSelector: {}

tolerations: []

affinity: {}
