{{- if and .Values.geth.persistence.enabled (not .Values.geth.persistence.existingClaim) (not .Values.geth.persistence.hostPath) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "ethereum.fullname" . }}
  labels:
    app: {{ template "ethereum.name" . }}
    chart: {{ template "ethereum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: geth
spec:
  accessModes:
    - {{ .Values.geth.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.geth.persistence.size | quote }}
  {{- if .Values.geth.persistence.storageClass }}
  {{- if (eq "-" .Values.geth.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.geth.persistence.storageClass }}"
    {{- end }}
  {{- end }}
{{- end -}}
