FROM smartbear/ready-api-virtserver:latest

ENV ACCEPT_TOU=true
ENV VirtServerUser=admin
ENV VirtServerPassword=SifChain4Life
ENV VirtServerUserRole=admin

ENV VirtServerLicenseServer=172.0.64.128:1099