#
# Main
#
FROM alpine

ENV PACKAGES curl jq bind-tools expect

EXPOSE 1317
EXPOSE 26656
EXPOSE 26657

RUN apk add --update --no-cache $PACKAGES

# extras for test suite
RUN apk add python3 vim bash yarn npm socat busybox-extras make go linux-headers git
RUN \
  # update packages
  apk update && apk upgrade && \
  # install ruby
  apk --no-cache add ruby ruby-dev ruby-bundler ruby-json ruby-irb ruby-rake ruby-bigdecimal && \
  rm -rf /var/cache/apk/*
RUN gem install rake
RUN wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq

RUN yarn config set cache-folder /yarncache