name: gitleaks

on: [push,pull_request]
  
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: .github/.gitleaks.toml