name: Run integration tests 3 for test chain (clp)
on:
  push:
    paths-ignore:
      - "ui/**"

jobs:
  integration:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sifchain/sifchain-devops
          path: deploy
          token: "${{ secrets.GIT_PAT }}"
      - name: Set up linux environment
        run: # installs development tools and updates .bash_profile
          bash test/integration/setup-linux-environment.sh
      - name: Setup integration test environment
        run: |
          source $HOME/.bash_profile
          bash test/integration/start-integration-env.sh
      - name: Execute test chain integration tests
        run: |
          source $HOME/.bash_profile
          . test/integration/vagrantenv.sh
          export LOG_LEVEL=DEBUG
          bash test/integration/execute_integration_tests_against_test_chain_clp.sh
