name: Run integration tests 2 for any chain (peg)
on:
  push:
    paths-ignore:
      - "ui/**"

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sifchain/sifchain-devops
          path: deploy
          token: "${{ secrets.GIT_PAT }}"

      - name: Set up linux environment
        run: # installs development tools and updates .bash_profile
          bash test/integration/setup-linux-environment.sh

      - name: Clean
        run: make clean

      - name: Build
        run: |
          source ~/.bash_profile
          make install

      - name: Start standalone peggy
        run: |
          source ~/.bash_profile
          export PATH=./test/integration/framework/venv/bin/python3:$PATH
          ./test/integration/framework/siftool run-env --geth

      # This sleep is needed for the tests to work
      - name: Run integration tests
        run: |
          source ~/.bash_profile
          ./test/integration/framework/siftool generate-python-protobuf-stubs
          sleep 30
          pushd test/integration && framework/venv/bin/python3 -m pytest -olog_level=DEBUG -olog_file=/tmp/int-test.out -v src/peggy2/test_eth_transfers.py src/peggy2/test_peggy2_wrong_signature.py

      # This is commented out because logs no longer outputs to that dir.
      # Will update with new location
      # - name: Archive logs from test
      #   uses: actions/upload-artifact@v2
      #   # The path is not where the logs reside. This is a temporary change to disable this action
      #   if: always()
      #   with:
      #     name: testlogs2
      #     path: test/integration
