name: Lint

on: [pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Set GOROOT (fix for https://github.com/golangci/golangci-lint/issues/3107)
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # TODO Upgrade golangci-lint version and fix errors reported by the new version
          version: v1.47.3
