name: Feature merged

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    env:
      WORKING_DIRECTORY: ./
      WORKSPACE_PREFIX: sifchain-aws
      WORKSPACE_NAME: feature-testnets
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create k8s config
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          mkdir -p .live/${{ env.WORKSPACE_PREFIX}}-${{ env.WORKSPACE_NAME }}
          aws eks --region us-west-2 update-kubeconfig \
                  --name ${{ env.WORKSPACE_PREFIX}}-${{ env.WORKSPACE_NAME }} \
                  --kubeconfig .live/${{ env.WORKSPACE_PREFIX}}-${{ env.WORKSPACE_NAME }}/kubeconfig_${{ env.WORKSPACE_PREFIX}}-${{ env.WORKSPACE_NAME }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Destroy namespace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          rake 'cluster:sifnode:destroy[${{ env.WORKSPACE_NAME }},aws,${{ env.GITHUB_HEAD_REF_SLUG }},true]'
