name: Publish Testnet Release Images

on:
  release:
    types:
      - created
    branches:
      - develop

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          make CHAINNET=${{ github.event.ref }} BINARY=sifnoded build-image
          make CHAINNET=${{ github.event.ref }} BINARY=sifnodecli build-image
          make CHAINNET=${{ github.event.ref }} BINARY=sifcrg build-image
          make CHAINNET=${{ github.event.ref }} BINARY=ebrelayer build-image
          cd ./api/openapi
          make CHAINNET=${{ github.event.ref }} build-image-swagger-iu
          make CHAINNET=${{ github.event.ref }} build-image-prism

      - name: Push images
        run: |
          docker push sifchain/sifnoded:${{ github.event.ref }}
          docker push sifchain/sifnodecli:${{ github.event.ref }}
          docker push sifchain/sifcrg:${{ github.event.ref }}
          docker push sifchain/swagger-ui:${{ github.event.ref }}
          docker push sifchain/prism:${{ github.event.ref }}
          docker push sifchain/ebrelayer:${{ github.event.ref }}
