name: Publish Testnet Images

on:
  push:
    branches: develop

jobs:
  testnet:
    name: testnet
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          make CHAINNET=testnet BINARY=sifnoded build-image
          make CHAINNET=testnet BINARY=sifnodecli build-image
          make CHAINNET=testnet BINARY=sifcrg build-image
          cd ./api/openapi && make CHAINNET=testnet build-image-swagger-iu
          cd ./api/openapi && make CHAINNET=testnet build-image-prim

      - name: Push images
        run: |
          docker push sifchain/sifnoded:testnet
          docker push sifchain/sifnodecli:testnet
          docker push sifchain/sifcrg:testnet
          docker push sifchain/swagger-ui:testnet
          docker push sifchain/prism:testnet
